### ISSUE TITLE
Communicator does't have a convenient testing harness

### ISSUE THREAD

**Issue by manualautomaton** [withtwoemms/recruitment#23]
**As a** lib User implementing a test
**I want** a version of a `Communicator` that allows me to compose responses
**So I** can avoid making external calls and can make assertions agains expected structs

**Comment by withtwoemms** [comment]
will likely make this feature apart of the official v0.4.0 release

**Comment by manualautomaton** [comment]
v0.4.0a2 works as intended!

**Comment by withtwoemms** [comment]
:::releasing v0.4.0:::
